[book]
authors = ["victoryang00"]
language = "cn"
multilingual = false
src = "."
title = "SlugWiki"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/victoryang00/wiki"
site-url = "/wiki/"
mathjax-support = true
